apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-runner
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /data/storage/kubernetes/gitlab-runner
    server: 192.168.1.200
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""